name: odoo
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  bloc: ^9.0.0
  flutter_bloc: ^9.1.1
  hydrated_bloc: ^10.1.0
  equatable: ^2.0.7
  get_it: ^8.0.3
  injectable: ^2.5.0
  path_provider: ^2.1.5
  json_annotation: ^4.9.0
  go_router: ^16.0.0
  uuid: ^4.5.1
  intl: ^0.20.2
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  json_serializable: ^6.9.5
  build_runner: ^2.5.4
  injectable_generator: ^2.7.0

flutter:
  uses-material-design: true
